version: '3.7'

services:
  db:
    container_name: upmeal-database
    image: mysql:8
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: upmeal
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin

volumes:
  db-data:
